version: '3.7'

services:

  adminer:
    image: adminer
    ports:
      - 5100:8080
    restart: always
    depends_on:
      - db

  integrator:
    environment:
      API_URL: http://api:5010/api
    depends_on:
      - api

  api:
    build:
      context: ./tools/api
      dockerfile: Dockerfile
    ports:
      - 5010:5010
